### PR TITLE
features of DAO

### PR DESCRIPTION
**Pull request by VadymPolianskyi**
Created BaseService and BaseRepository

### CODE REVIEW

**Comment by Dominys** [comment]
@VadymPolyanski Did i approve this ???

**Comment by VadymPolianskyi** [comment]
But you have not write anything after your review...) And I have decided that everything is alright.

**Comment by Dominys** [comment]
@VadymPolyanski I did not approve your PRs

**Comment by VadymPolianskyi** [comment]
@Dominys, my code is working) And I have changed my code according to your recomendations. I understood, that I must wait your OK. I will do it henceforth, promise.

**Comment by Dominys** [comment]
@VadymPolyanski If you are writing so perfect code that you don't need PR approve - than what did you missed on our course ?

**Comment by VadymPolianskyi** [comment]
@Dominys We spoke in skype yesterday.. You allowed me not revert this PR) And I will not repeat it henceforth. I understood my mistake. I will create a separate branch to each task!

**Pull request merged**
